{% set name = "fixie" %}
{% set version = "0.0.4" %}
{% set sha256 = "7688b8ceef2c39f39c35170391bff1ce5367a4ad80c5a7b4cf9092bc3d87fc97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - xonsh
    - cerberus
    - tornado
    - lazyasd

test:
  requires:
    - python {{ python_min }}
  imports:
    - fixie
    - fixie.environ

about:
  home: http://github.com/ergs/fixie
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Cyclus-as-a-Service'

extra:
  recipe-maintainers:
    - scopatz
